### PR TITLE
Credit-based flow control support

### PR DESCRIPTION
**Pull request by zhemao**
This bumps firechip for the credit-based flow control RTL and updates the switch model to support it. It's turned off by default, and I tested that these changes work with the canonical image for dev.

### CODE REVIEW

**Comment by zhemao** [comment]
Related PRs for submodules

https://github.com/firesim/firesim-software/pull/18

https://github.com/firesim/network-benchmarks/pull/3

https://github.com/firesim/firechip/pull/21

**Comment by zhemao** [comment]
iperf3 simulation performance on dev:

time elapsed: 819.3 s, simulation speed = 43.74 MHz
FPGA-Cycles-to-Model-Cycles Ratio (FMR): 2.11

iperf3 simulation performance on this branch:

time elapsed: 825.9 s, simulation speed = 43.37 MHz
FPGA-Cycles-to-Model-Cycles Ratio (FMR): 2.13

**Comment by sagark** [comment]
@zhemao can you merge dev into this and generate fresh AGFIs?

**Comment by zhemao** [comment]
Outdated because we're using ethernet pause frames instead.

**Pull request closed without merging**
