### PR TITLE
Bump chipyard, rm bintray due to sunset

### PR DESCRIPTION
**Pull request by timsnyder-siv**
Trying to detangle the timeout I'm seeing in #651 and also locally when I don't have the changes from #651 but only bump chipyard.  Seeing if I can reproduce the timeout by only bumping chipyard in firesim as top in the CI.

### CODE REVIEW

**Comment by timsnyder-siv** [comment]
Whell, now the CI is failing for a completely unrelated reason having to do with https://sbt.bintray.com being down. I thought that it might be some kind of Sunday-night maintenance but going to bintray.com it looks like the service is being sunset:
image

**Comment by timsnyder-siv** [comment]
When I search scala-sbt.org for 'rpm' [the result I get is mostly in chinese (maybe? based on zh-cn in url) ](https://www.scala-sbt.org/1.x/docs/zh-cn/Installing-sbt-on-Linux.html#%E7%BA%A2%E5%B8%BD%E4%BC%81%E4%B8%9A%E7%89%88Linux%E5%92%8C%E5%85%B6%E4%BB%96%E5%9F%BA%E4%BA%8ERPM%E7%9A%84%E5%8F%91%E8%A1%8C%E7%89%88)

Oh, and I did find https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ which does say that bintray.com is offline as of May 1, 2021.

I'm going to try switching the machine-launch.sh script to using the sbt-rpm.repo from scala-sbt.org and see if that works.

**Comment by timsnyder-siv** [comment]
@davidbiancolin , I grepped for bintray in Chipyard and only found it in the docs.  Might want to update those before the release.  I filed https://github.com/ucb-bar/chipyard/issues/873 to let them know.

**Comment by timsnyder-siv** [comment]
Ok.  Now run-test-groupB is failing during `build-setup.sh` because cloning stuff from git.qemu.org is failing.  When I browsed there, I also got a 503 :
image

I wonder if they are experiencing a DDoS or just heavy load.  When I went to https://www.qemu.org/contribute/, I see that they have their code mirrored on gitlab now too.  That might have better load handling depending on what they have behind git.qemu.org.

**Comment by timsnyder-siv** [comment]
It looks like AXI4Fuzzer is still hanging even after adding `libfesvr.a` to the `DRIVER_CC` in the `fasedtests` makefrag.  I'm trying to repro this in a clean clone again.

**Comment by davidbiancolin** [comment]
I'll SSH onto the CI instance and see what's gongi on.

**Comment by davidbiancolin** [comment]
It appears you're doing that already!

**Comment by timsnyder-siv** [comment]
@davidbiancolin and I traced this back to the ML-sim running very slow when using dramsim2 because it has been updated to take a `clock_hz` that the testchipip wrapper class wasn't properly initializing in all of it's constructors.  Opened https://github.com/ucb-bar/testchipip/pull/132 with proposed fix.

**Comment by timsnyder-siv** [comment]
@davidbiancolin I bumped Chipyard to use the testchipip bump in ucb-bar/chipyard#878 before it has merged.  We can wait to merge this if you want.  I just wanted to see that the CI passes with the testchipip fix.

**Comment by timsnyder-siv** [comment]
ucb-bar/chipyard#878 has merged.  @davidbiancolin we can probably merge this anytime now if you agree.

**Review by davidbiancolin — APPROVED** [review]
We're going to ship this without AGFI generation (I will do that in a separate PR) because CI is doubly broken without this bump.

**Pull request merged**
