### PR TITLE
Adds quad-core BOOM target config

### PR DESCRIPTION
**Pull request by farzadfch**
This PR adds a quad-core BOOM config. I've built the AGFI and booted Linux.
The maximum number of hart ID bits must be set according to the number of BOOM tiles, otherwise, we get an error at elaboration phase.

### CODE REVIEW

**Comment by farzadfch** [comment]
`FireSimBoomConfig` does not instantiate an object of `WithNDuplicatedBoomCores`. So this code does not have to work with n=1.
Even if we had a config with `WithNDuplicatedBoomCores(1)`, it would work as well becuase `log2Ceil(1)` returns 1. I can compile with such a config and test it, if you want.

**Comment by jerryz123** [comment]
I think `log2Ceil(1)` returns 0. 

https://github.com/freechipsproject/chisel3/blob/9f77bf54543724594711f0455ef91f51edfbd22e/src/main/scala/chisel3/util/Math.scala#L34-L45

**Comment by jerryz123** [comment]
Also I am going to change FireSim to use a normal BoomConfig, instead of the SmallBoomConfig it is currently building (#272). BoomConfig is a more reasonable representation of a high performance core, but it does use more FPGA resources. You will probably be unable to synthesize a quad-core BOOM with the larger configuration.

**Comment by davidbiancolin** [comment]
I've synthesized quad core, default boom, it fits.

**Comment by davidbiancolin** [comment]
+1 for log2up.

**Comment by farzadfch** [comment]
@jerryz123 SmallBoomConfig better suits my purpose as I may eventually integrate NVDLA with BOOM and default BOOM most probably won't fit. If you can please keep the option for SmallBoomConfig alongside default BOOM (if you can't that's also fine).

**Comment by davidbiancolin** [comment]
No worries, we will keep the small config around because it's good for pipe cleaning and debugging other parts of the flow.

**Pull request merged**
