### PR TITLE
Update FireSimBoomConfig to use normal sized BOOM

### LINKED ISSUE #266: Use larger BoomConfig instead of current SmallBoomConfig
Since wider systembuswidths are supported now.

### PR DESCRIPTION
**Pull request by jerryz123**
Resolves #266

### CODE REVIEW

**Comment by davidbiancolin** [comment]
This will require AGFI regeneration, at least for the BOOM designs.

**Comment by farzadfch** [comment]
Quad-core normal size BOOM fails at placement. Memory model: FR-FCFS, 4MB LLC
```
[192.168.5.220] out: ERROR: [Place 30-487] The packing of instances into a set of CLBs defined by a pblock constraint could not be obeyed. There are a total of 111900 CLBs in the pblock, o
f which 29331 CLBs are available, however, the unplaced instances require 31140 CLBs. The unavailable CLBs are either taken by placed instances or are blocked due to exclude placement cons
traints. Please analyze your design to determine if the pblock can be resized or the number of LUTs, FFs, and/or control sets can be reduced.
[192.168.5.220] out: 
[192.168.5.220] out: Number of control sets and instances constrained to the pBlock
[192.168.5.220] out:    Control sets: 15198
[192.168.5.220] out:    Luts: 938332 (combined) 940131 (total), available capacity: 895200 
[192.168.5.220] out:    Flip flops: 492514, available capacity: 1790400
[192.168.5.220] out:    NOTE: each CLB can only accommodate up to 4 unique control sets so FFs cannot be packed to fully fill every CLB
```

**Comment by sagark** [comment]
IMO we shouldn't silently change existing configs --- we should add a new config. If the issue is that we don't want people defaulting to the old config (since the name sounds like the "default"), then we should change the old one's name too, so that people using it notice that it has changed (because builds will fail).

**Comment by jerryz123** [comment]
This is now done in Chipyard. Closing

**Pull request closed without merging**
