### PR TITLE
add test and train input size options for spec17 workload; bump Speckle

### PR DESCRIPTION
**Pull request by cookiestuf**
invoke like so: `make spec-intspeed input=test`. Please note there's currently a SPEC regression, so you won't have a clean run. https://github.com/firesim/firesim/issues/133

### CODE REVIEW

**Comment by sagark** [comment]
Can you add a note here that shows how to change the input size?

docs/Advanced-Usage/Workloads/SPEC-2017.rst

Besides that, LGTM!

**Comment by cookiestuf** [comment]
Do you want me to do this on the docs branch or dev branch?

**Comment by sagark** [comment]
dev. So you can just merge this as is.

**Comment by hz1490919302** [comment]
How to use Firesim-Spec2017,
Do I need to buy SPEC2006 v1.2 or SPEC2017 v1.1.5?

**Comment by davidbiancolin** [comment]
Hey Mike, 

SPEC2017 would be easier to run out of the box, but with some extra work it's very possible to use 2006. 

Also, since you've asked this question in multiple places, in the future I'd suggest posting to our google groups in the future:
https://groups.google.com/g/firesim

**Pull request closed without merging**
