### PR TITLE
combine with sequencer's #747, #749 and #750 patches

### PR DESCRIPTION
**Pull request by SihaoLiu**
This PR just combines @sequencer 's #747, #749 and #750 pull request with one minor changes:

remove the first commit of #747 (docs changes, which is already modified)

### CODE REVIEW

**Comment by davidbiancolin** [comment]
Hey SihaoLiu!

Lets get #780 in first, and then see what remains. 

In the future you need to open PRs against the "dev" branch, since we leave master as a relative stable release.

**Comment by SihaoLiu** [comment]
> Hey SihaoLiu!
> 
> Lets get #780 in first, and then see what remains.
> 
> In the future you need to open PRs against the "dev" branch, since we leave master as a relative stable release.

Oh sorry, sure I will close this PR

**Comment by davidbiancolin** [comment]
I appreciate the contribution :)

**Comment by sequencer** [comment]
Sorry I was on other projects these days, FireSim localization is a little stale, but I and @SihaoLiu will continue work on it with VCU118.

**Pull request closed without merging**
