### PR TITLE
Fix deprecations for up-to-date chisel/FIRRTL API

### PR DESCRIPTION
**Pull request by sequencer**
I'm compiling firesim on my local machine(without Makefile), which leads to dependency issues.
This PR replace toBool with asBool and remove all reference to chisel3.core and chisel3.driver, these change has been upstreamed in chipsalliance/chisel3#1730.
I also remove QoRShiGenerator, Since I didn't find any reference to it(including makefile).

### CODE REVIEW

**Review by davidbiancolin — COMMENTED** [review]
I have used the QoRShimGenerator recently (last week actually), could you not delete that yet?

Also these aren't breakages yet right, since you're not bumping a major version?

**Comment by davidbiancolin** [comment]
Otherwise it LGTM -- thanks for your contribution. :)

**Comment by sequencer** [comment]
> I have used the QoRShimGenerator recently (last week actually), could you not delete that yet?

Sure I'll keep this, I just rebased that commit to my next PR, and I think this one is safe to merge now.
Do I need to port QoRShimGenerator to Stage/Phase API? Although It will take some time to deal with, I can spare some days on it.

> Also these aren't breakages yet right, since you're not bumping a major version?

Yes, I still don't understand how to bump and not dare to change the build system(since I have no environment to give a test), thus I choose to implement the build system on my own [repo](https://github.com/sequencer/chipsalliance-playground/blob/master/build.sc) with mill, so besides some compatibility code PR, I won't submit build system related change currently.

**Comment by sequencer** [comment]
I forgot to update sources under `sim/src/main/scala`
2aa2c5d give a update, needs a re-review

**Comment by davidbiancolin** [comment]
> Sure I'll keep this, I just rebased that commit to my next PR, and I think this one is safe to merge now.
> Do I need to port QoRShimGenerator to Stage/Phase API? Although It will take some time to deal with, I can spare some days on it.

Don't worry about porting it, it's not worth your time.

**Comment by davidbiancolin** [comment]
@sequencer Could you just squash all these commits. That will trigger a CI run (which i've enabled to run on forks).

**Comment by sequencer** [comment]
reopen and PR to origin/dev

**Pull request closed without merging**
